version: '3'
services:
  card-creator:
    image: "zwaq/tunequest-card-creator:1.0.0"
    restart: always
    ports:
      - 2346:80
    environment:
      SPOTIFY_REDIRECT_URI: https://create.tune-quest.de/
      SPOTIFY_CLIENT_ID: ???

  tunequest:
    image: "zwaq/tunequest:1.0.0"
    restart: always
    ports:
      - 2345:3000
    environment:
      SPOTIFY_AUTHORIZE_URL: https://accounts.spotify.com/authorize
      SPOTIFY_API_TOKEN_URL: https://accounts.spotify.com/api/token
      SPOTIFY_SCOPES: "user-modify-playback-state streaming user-read-email user-read-private"
      SPOTIFY_CLIENT_ID: ???
      SPOTIFY_CLIENT_SECRET: ???
      SPOTIFY_REDIRECT_URI: https://play.tune-quest.de/player
      TUNEQUEST_CREATE_URL: https://create.tune-quest.de
